### ISSUE TITLE
Could not start debugger after configureation

### ISSUE THREAD

**Issue by guozebin** [DonJayamanne/javaVSCode#10]
It's great to debug java program inside Visual Studio Code, 
but I could not start the debugger after configuration.(JDK is installed (version 1.7.0 and later), Path to jdk is configured in launch.json)
It seems that some people meet the same problem.

OS:         win 7 pro x64
JDK:        jdk1.8.0_91 x86
VSC:        13.1

**Comment by faustinoaq** [comment]
@guozebin Are you still with the problem?

I'm working with javaVSCode now.

OS: Manjaro KDE Fringilla
JDK: java-8-openjdk
VSC: 1.6.1

**Comment by guozebin** [comment]
Yes, I am still confused.

---

发件人: Faustino Aguilar notifications@github.com
发送时间: 2016年10月25日 23:13
收件人: DonJayamanne/javaVSCode
抄送: guozebin; Mention
主题: Re: [DonJayamanne/javaVSCode] Could not start debugger after configureation (#10)

@guozebinhttps://github.com/guozebin Are you still with the problem?

I'm working with javaVSCode now.

OS: Manjaro KDE Fringilla
JDK: java-8-openjdk
VSC: 1.6.1

―

**Comment by faustinoaq** [comment]
@guozebin See #17
