### ISSUE TITLE
Clicking 'Run' does not advance to next breakpoint

### ISSUE THREAD

**Issue by mfs409** [DonJayamanne/javaVSCode#11]
I have stopOnEntry set to true in my launch.json.  After the program starts, I can see that I'm on the first executable line in the main function.  At this point, if I use F9 to add breakpoints to the program (for example, on the very next line), then the red dot appears in VSCode, and the Breakpoints window shows that a breakpoint has been added.  But if I press F5 or click the green Run button to continue, the program runs through the breakpoints, all the way to completion.

**Comment by faustinoaq** [comment]
@mfs409 see #16
