### ISSUE TITLE
Debugging Spring Boot Applications?

### ISSUE THREAD

**Issue by ldiego08** [DonJayamanne/javaVSCode#13]
Hi! I'm currently using Maven to create an application using Spring Boot, following this tutorial: [Serving Web Content with Spring MVC](https://spring.io/guides/gs/serving-web-content/) As the tutorial points out, by running the `main` method in the `Application` class, you should be able to start your web application as if it was a console app. Now, when I hit debug, the `main` method seems to execute just fine (I can step through and all,) but whenever requesting for `localhost:8080/greeting` I get an error saying there's no server listening on port 8080. This happens only when I try to execute the application through the vs code Java debugger - if I create an executable jar or run it using Maven, it works perfect. 

What exactly does this debugger does differently that the application won't boot like it should? Am I missing something? 

Attached you'll find my `pom.xml`, `launch.json`, and `tasks.json` files. Any help with this would be very much appreciated.

[config_files.zip](https://github.com/DonJayamanne/javaVSCode/files/465167/config_files.zip)

**Comment by faustinoaq** [comment]
@ldiego08 @DonJayamanne But, javaVSCode support _attach_ like [pythonVSCode](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python) debugging?

EDIT: (answer to myself :sweat_smile: )
yes it do
Start server using `java -agentlib:jdwp=transport=dt_socket,server=y,address=3003 ClassName`

**Comment by khe817** [comment]
I am not sure if @ldiego08 has made it work for debugging spring boot. But here is how I manage to run the debugger with maven:

Supposingly the class we want to debug is a controller in src/main/java/hello/HelloController.java ; And the spring boot project has already been built/packaged to a jar file ($ mvn package ).

In launch.json:
 ```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Java",
            "jdkPath": "${env.JAVA_HOME}/bin",
            "type": "java",
            "request": "launch",
            "stopOnEntry": true,
            "cwd": "${workspaceRoot}/src/main/java",
            "startupClass": "hello.Application",
            "options": [
                "-jar",
                "${workspaceRoot}/target/gs-spring-boot-0.1.0.jar"
            ]
        }
    ]
}

```

startupClass should be the class that contains the main method (in this case, Application.java).

***Steps for debugging:***
- Add a break point in a controller's method (e.g. @RequestMapping("/greeting") ).
- Run the debugger (F5).
- Hit run when it stops at the main method in Application class.
- Call to that controller in browser/cli (e.g. $ curl  localhost:8080/greeting/).
- This time the debugger will stop at the break point in the controller.
- Happy debugging.

:)

**Comment by khe817** [comment]
I have found another way to debug Spring Boot without having to run mvn package first (boot up faster), by using remote debugging. Here is how I manage to run the debugger with maven:

In launch.json (updated for 0.1.4 version):
 ```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Java Remote",
            "jdkPath": "${env.JAVA_HOME}/bin",
            "type": "java",
            "request": "attach",
            "stopOnEntry": true,
            "cwd": "${workspaceRoot}",
            "startupClass": "${relativeFile}",
            "startupClassPathPattern": "src/main/java/",
            "sourcePath": ["${workspaceRoot}/src/main/java"],
            "classpath": ["${workspaceRoot}/target/classes"],
            "remoteHost": "localhost",
            "remotePort": 5005
        }
    ]
}

```

***Steps for debugging:***
- Run Spring Boot web app server with opened port 5005 for debugging:
```
$ mvn spring-boot:run -Drun.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"
```
- Add a break point in a controller's method. The controller file must be the currently focused window in VSCode.
- Run the debugger (F5).
- Hit run when it stops at a method in SilentExitExceptionHandler class.
- Call to that controller in browser/cli (e.g. $ curl  localhost:8080/greeting/).
- This time the debugger will stop at the break point in the controller.
- Happy debugging.

:)

**Comment by arcseldon** [comment]
@khe817 - followed your instructions above. the first instructions worked for the helloworld spring sample but not for my app.

The remote debugger option above - keep getting this error in VSC when i start the debugger launcher.

```
Error:spawn ${env.JAVA_HOME}/bin/jdb ENOENT
```

Any ideas?

If I stop the springboot:run session (shut down the remote debug session) then try the Launcher i get:

```
Failed to start jdb, java.net.ConnectException: Connection refused
```

So, that error I can understand. The previous one regarding `jdb` less clear about - PATH or JAVA_HOME configuration problems?

**Comment by khe817** [comment]
@arcseldon , I think you have to change the `"jdkPath"` config to your Java path if you don't have JAVA_HOME configured in vscode settings. Something like this:
```json
"jdkPath": "C:/Program Files/Java/jdk1.8.0_112/bin",
```

In the first way to run the debugger (running it with jar file), you will need to change `"startupClass"` to the start up class of the application that contains the `public static void main(String[] args) {}` method.
If the start up class with the `public static void main(String[] args) {}` method locates in `/src/main/java/com/mycompany/Application.java` , the configuration in launch.json should look like this:
```json
"cwd": "${workspaceRoot}/src/main/java",
"startupClass": "come.mycompany.Application",
```

I need to see your launch.json and your project folder structure to offer any more advice.

**Comment by arcseldon** [comment]
@khe817 - Thanks very much for response. Solved the issue & your suggested script (second one, using remote debug) works as expected. Not absolutely clear I changed anything - believe the port I was starting the server up on (not the 5005 debug attach port) was already taken - as when I discovered this and killed it, subsequent attempts were good afaik.  Anyhow, all set - thank you again!

**Comment by arcseldon** [comment]
One minor gripe and warning to others (@khe817 - you pointed this out too), you need to have the Class with the main method (eg. App.java) open and ready with a debug breakpoint in the editor when you run the `mvn spring-boot:run` command. It seems to get lost otherwise, and remains zombied.

**Comment by faustinoaq** [comment]
> . Solved the issue & your suggested script (second one, using remote debug) works as expected.
