### ISSUE TITLE
Debugger failed to attach: handshake failed - connection prematurally closed

### ISSUE THREAD

**Issue by micturkey** [DonJayamanne/javaVSCode#14]
Hello, It's really exciting for me to debug java programs in VSCode.
But if I choose Java Console App, it pops up a window and says "Debugger failed to attach: handshake failed - connection prematurally closed".
I am a beginner so I cannot work out what has happened.
By the way, if I choose Java, nothing happened.

**Comment by jakoberzar** [comment]
Have you tried setting breakpoints, does the code stop where it gets to that line? 
The Java Console App configuration is useful because it opens up a console in which Scanner can read your input.
I get the same error as you did, but it still works normally nonetheless.

**Comment by micturkey** [comment]
@jakoberzar Thanks for your reply.
 I tried setting breakpoints, but it cannot stop where it gets to that line.
And Scanner doesn't work in the Java Console App.

**Comment by faustinoaq** [comment]
@jakoberzar  @zhaidoudou123 see #16

**Comment by faustinoaq** [comment]
See #8
