### ISSUE TITLE
jdkPath problem in Linux

### ISSUE THREAD

**Issue by leniel** [DonJayamanne/javaVSCode#15]
I'm trying to debug Java code using your extension but it isn't working in my Linux virtual machine.

It keeps showing the message `Starting Java Language Server` as shown in the screenshot's footer below:

![screenshot from 2016-10-13 19-02-43](https://cloud.githubusercontent.com/assets/764854/19368792/1c62b282-9178-11e6-9bf9-b18365696b2e.png)

My `launch.json` is as follows:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "jdkPath": "/usr/lib/jvm/java-8-oracle/bin",
            "name": "Java",
            "type": "java",
            "request": "launch",
            "stopOnEntry": true,
            "cwd": "${fileDirname}",
            "startupClass": "${fileBasename}",
            "options": [
                "-classpath",
                "\"${fileDirname};.\""
            ]
        },
        {
            "jdkPath": "/usr/lib/jvm/java-8-oracle/bin",            
            "name": "Java Console App",
            "type": "java",
            "request": "launch",
            "stopOnEntry": true,
            "cwd": "${fileDirname}",
            "startupClass": "${fileBasename}",
            "options": [
                "-classpath",
                "\"${fileDirname};.\""
            ],
            "externalConsole": true
        }
    ]
}
```

**Comment by DonJayamanne** [comment]
@leniel 

> Starting Java Language Server

This message is displayed by some other extension you have installed.

> but it isn't working in my Linux virtual machine
- Please could you open the developer tools (Help->Developer Tools) and check if any errors are logged in the console window.

**Comment by faustinoaq** [comment]
Yes, @DonJayamanne @leniel the message `Starting Java Language Server` is from [RedHat Java](https://marketplace.visualstudio.com/items?itemName=redhat.java) or [Java Language Support](https://marketplace.visualstudio.com/items?itemName=georgewfraser.vscode-javac) extensions and both require a full Maven or Gradle project.

**Comment by DonJayamanne** [comment]
@faustinoaq , thanks. 

> Please could you open the developer tools (Help->Developer Tools) and check if any errors are logged in the console window.

Any success here?

**Comment by faustinoaq** [comment]
@DonJayamanne all is working fine but when java package isn't used.
Also no errors in devTools.

My `launch.json`:

> Note: ${workspaceRoot} is required for classpath

``` json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Java",
      "type": "java",
      "request": "launch",
      "stopOnEntry": true,
      "jdkPath": "/usr/lib/jvm/default/bin",
      "cwd": "${fileDirname}",
      "startupClass": "Hello",
      "options": [
        "-classpath",
        "${workspaceRoot}/bin/mypackage"
      ]
    }
  ]
}
```

A simple sample:

> Note: the package is commented, because breakpoints don't work when package exist. see #16 

![javaVSCode](http://i.imgur.com/SkfYoZR.png)

> Also, when package exist (mypackage is uncommented), the devTools don't show errors

**Comment by faustinoaq** [comment]
@DonJayamanne Also, I did my own extension, you can take a look of my [Java Linter](https://marketplace.visualstudio.com/items?itemName=faustinoaq.javac-linter) when you want.
Bye! :raising_hand_man:
