### ISSUE TITLE
How to configure build task and debug config

### ISSUE THREAD

**Issue by damien122** [DonJayamanne/javaVSCode#17]
Hi,
could you please explain how to configure the build task and the debug config?
Because I can't find any information about it and it's not self-evident.
With the build script from you I got the error "javac is not found".
I have installed JDK 8.112

**Comment by damien122** [comment]
after adding this 
"jdkPath": "C:\Program Files\Java\jdk1.8.0_112\bin",
to the launch.json and task.json somthing changed.
I could start the debugger but it cant find my main class.
And the build task still not work.

this is the content of my task.json:
{
    "version": "0.1.0",
    "command": "javac",
    "isShellCommand": true,
    "showOutput": "always",
    "isWatching": true,
    "jdkPath": "C:\Program Files\Java\jdk1.8.0_112\bin",
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "build",
            "args": ["-g", "${file}"]
        }
    ]
}

and this is the content of my launch.json:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Java",
            "type": "java",
            "request": "launch",
            "stopOnEntry": true,
            "cwd": "${fileDirname}",
            "jdkPath": "C:\Program Files\Java\jdk1.8.0_112\bin",
            "startupClass": "${fileBasename}",
            "options": [
                "-classpath",
                "\"${fileDirname};.\""
            ]
        },
        {
            "name": "Java Console App",
            "type": "java",
            "request": "launch",
            "stopOnEntry": true,
            "cwd": "${fileDirname}",
            "jdkPath": "C:\Program Files\Java\jdk1.8.0_112\bin",
            "startupClass": "${fileBasename}",
            "options": [
                "-classpath",
                "\"${fileDirname};.\""
            ],
            "externalConsole": true
        }
    ]
}

**Comment by faustinoaq** [comment]
@damien122 
My `launch.json` on Windows 10:

``` json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Java",
      "type": "java",
      "request": "launch",
      "stopOnEntry": true,
      "jdkPath": "C:/Program Files/Java/jdk1.8.0_112/bin",
      "cwd": "${workspaceRoot}/src",
      "startupClass": "Main",
      "options": [
        "-classpath",
        "${workspaceRoot}/bin"
      ]
    }
  ]
}
```

> Note: ${workspaceRoot} is needed

My project tree:

```
MyProject/
    bin/
        Main.class
    src/
        Main.java
```

**Comment by damien122** [comment]
sry but this don't change any thing ... I can't use Java with VSCode.
Build and Debug don't work for me.

**Comment by faustinoaq** [comment]
@damien122 Oh, javaVSCode works perfectly for me. My only issue is #16 

Are you sure that `launch.json` is correctly configured?

Try some more simple:

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Java",
      "type": "java",
      "request": "launch",
      "stopOnEntry": true,
      "jdkPath": "C:/Program Files/Java/jdk1.8.0_112/bin",
      "cwd": "${workspaceRoot}",
      "startupClass": "Main",
      "options": [
        "-classpath",
        "${workspaceRoot}"
      ]
    }
  ]
}
```

Project tree:

```
MyProject/
    .vscode/
        launch.json
    Main.class
    Main.java
```

> Note: I use `/` instead of `\\` and ${workspaceRoot} instead of ${filepath}

**Remember:** JavaVSCode is for debugging only. You must compile your `.java` code via commandline with `javac -g Main.java`. You can use `tasks.json` for compilation or a extension like [Java Linter](https://marketplace.visualstudio.com/items?itemName=faustinoaq.javac-linter).

Bye :raising_hand_man:

**Comment by alanwei43** [comment]
![vs-code-java-debugger](https://cloud.githubusercontent.com/assets/2927578/19837518/518be54c-9ef6-11e6-96c8-1b4edc254748.png)
![vs-code-java-debugger-warning](https://cloud.githubusercontent.com/assets/2927578/19837519/56c36382-9ef6-11e6-94ad-e4e87fa7688a.png)

How to resolve  Source \HelloWorld.java is not avaialble?

**Comment by faustinoaq** [comment]
@Allen-Wei

```
"cwd": "${workspaceRoot}/src/net.alanwei"
```

or when HelloWorld.java tab is selected

```
"cwd": "${fileBasename}"
```

![example](http://i.imgur.com/b5ZyeMm.png)

**Comment by alanwei43** [comment]
@faustinoaq It works ! Thansk you very much.
