### ISSUE TITLE
could't run java debug after config the launch.json and task.json

### ISSUE THREAD

**Issue by kangyabo** [DonJayamanne/javaVSCode#26]
And get a error which shows "Failed to start the program, Error: spawn /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/java ENOENT"

**Comment by jzalden** [comment]
That error means that it can't find the java runtime executable. (ENOENT stands for Error NO ENTry)
Can you post your tasks and launch.json files?

**Comment by kangyabo** [comment]
my launch.json file:

{
    "version": "0.2.0",
    "configurations": [
        
        {
            "jdkPath": "/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home",
            "name": "Java",
            "type": "java",
            "request": "launch",
            "stopOnEntry": true,
            "cwd": "${fileDirname}",
            "startupClass": "${fileBasename}",
            "options": [
                "-classpath",
                "\"${fileDirname};.\""
            ]
        },
        {
            "jdkPath": "/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home",
            "name": "Java Console App",
            "type": "java",
            "request": "launch",
            "stopOnEntry": true,
            "cwd": "${fileDirname}",
            "startupClass": "${fileBasename}",
            "options": [
                "-classpath",
                "\"${fileDirname};.\""
            ],
            "externalConsole": true
        }
    ]
}

my task.json file:

{
    "version": "0.1.0",
    "command": "javac",
    "isShellCommand": true,
    "showOutput": "always",
    "isBackground": true,
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "build",
            "args": ["-g", "${file}"]
        }
    ]
}

**Comment by kangyabo** [comment]
my launch.json:

{
    "version": "0.2.0",
    "configurations": [
        
        {
            "jdkPath": "/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home",
            "name": "Java",
            "type": "java",
            "request": "launch",
            "stopOnEntry": true,
            "cwd": "${fileDirname}",
            "startupClass": "${fileBasename}",
            "options": [
                "-classpath",
                "\"${fileDirname};.\""
            ]
        },
        {
            "jdkPath": "/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home",
            "name": "Java Console App",
            "type": "java",
            "request": "launch",
            "stopOnEntry": true,
            "cwd": "${fileDirname}",
            "startupClass": "${fileBasename}",
            "options": [
                "-classpath",
                "\"${fileDirname};.\""
            ],
            "externalConsole": true
        }
    ]
}

my task.json file:

{
    "version": "0.1.0",
    "command": "javac",
    "isShellCommand": true,
    "showOutput": "always",
    "isBackground": true,
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "build",
            "args": ["-g", "${file}"]
        }
    ]
}

Thx for help.

**Comment by i5on9i** [comment]
@kangyabo jdkPath should be the path which has a java.exe. In my case, it is "c:\Program Files\Java\jdk1.8.0_121\bin"

**Comment by kangyabo** [comment]
@i5on9i  there is not a java.exe file in my mac.

**Comment by i5on9i** [comment]
@kangyabo I think you have a file with another filename, such as java without extendion, in your bin folder. Anyway I meant that you should set your jdkPath to ".../bin"

**Comment by xybean** [comment]
@kangyabo did you fix it？

**Comment by kangyabo** [comment]
@xybean No,and I go back to IDEA

**Comment by viniciuscr** [comment]
its says jdkPath, but what it wants is the bin folder.
`/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/java/bin`
should work for you.

**Comment by jyan16** [comment]
I have the same problem,... and /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/java/bin

doesn't work.. help me!

**Comment by viniciuscr** [comment]
kangyabo  jdk was at  "/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/java"
are u sure that your jdk is in the same place?

mine is "C:\\Program Files\\Java\\jdk1.8.0_121\\bin"

**Comment by jyan16** [comment]
am sure. this is the path on Mac

**Comment by faustinoaq** [comment]
Now `launch.json` have been changed, take a look.
