### ISSUE TITLE
Error: Could not find or load main class TestingJava

### ISSUE THREAD

**Issue by customBoks** [DonJayamanne/javaVSCode#28]
@faustinoaq Hi , i had a problem with them , work's on Kde too and i do , i think the same thing like you but i have always the msg in my debug console "Error: Could not find or load main class TestingJava" , 2day i'am on but nothing.

![errordebugger](https://cloud.githubusercontent.com/assets/26315783/23779835/219a220a-0543-11e7-8cbd-61d0cc4e5d84.png)

![errordebugger2](https://cloud.githubusercontent.com/assets/26315783/23779838/27d57f98-0543-11e7-8f2b-c185f14cdf4e.png)

**Comment by faustinoaq** [comment]
Hi @customBoks 

Here you are :point_down: 

![image4547](https://cloud.githubusercontent.com/assets/3067335/23781045/a8442c2c-0518-11e7-8d83-cb21b3144258.png)
![screenshot_20170309_223628](https://cloud.githubusercontent.com/assets/3067335/23781081/e1c2e448-0518-11e7-8d68-88e78f565e12.png)

**Comment by customBoks** [comment]
Hi my friend,

I 'm so sad we had the same os but your tip's don't work on my vsc debugger.

**Comment by customBoks** [comment]
i'm doing the correction but nothing, again my setting
![errordebugger3png](https://cloud.githubusercontent.com/assets/26315783/23791707/627e576e-0584-11e7-8df7-cf14b10e5872.png)

![errordebugger4](https://cloud.githubusercontent.com/assets/26315783/23791740/78bcea5e-0584-11e7-8a4c-d4be5fa975d6.png)

**Comment by customBoks** [comment]
and this is my all extension , i don't see when i wrong but i'd one question maybe there are a relation ,
you know when i compile my TestingJava.java vscode don't create the TestingJava.class. or i don't see where is set.
The other programs you see on second scan i do it with another editor "DrJava" and he create me .class at the compilation 

![errordebugger5](https://cloud.githubusercontent.com/assets/26315783/23792312/b27b1f66-0586-11e7-95ae-fc2533e247c6.png)
![errordebugger6](https://cloud.githubusercontent.com/assets/26315783/23792317/b6c6fb6c-0586-11e7-88cc-cf80c043f4e8.png)

**Comment by faustinoaq** [comment]
Your JavaDebugger can't see TestingJava.java file because is wrong located inside `.vscode` directory. :sweat_smile: 

Try open new folder with just 2 files: `TestingJava.java` and `TestingJava.class` and `.vscode/launch.json`.
Compile `TestingJava.java` manually: `javac -g TestingJava.java`
Use the same `launch.json` in above comments.

**Comment by customBoks** [comment]
look , i create a new directory "vscode" and a new file my "TestJava.java" and he create the class file when i compile for this step is good sorry for my last question about the class file i don't saw but now is good.

next i try to put the complete path in lauch.json but again the same error
 
![errordebugger7](https://cloud.githubusercontent.com/assets/26315783/23795793/afc6e83e-0597-11e7-8ef9-1f915c8c3b14.png)

![errordebugger8](https://cloud.githubusercontent.com/assets/26315783/23795798/b9b4b2c2-0597-11e7-90ad-744f5e093edb.png)

**Comment by faustinoaq** [comment]
Look at your startupClass, You changed it.

Should be `"startupClass": "TestJava"`

**Comment by customBoks** [comment]
yes i now i change it because i try different thing's , and i back with "startupClass": "TestJava" but nothing change ...

**Comment by customBoks** [comment]
it's verry strange

**Comment by faustinoaq** [comment]
Also you are using `${workspaceRoot};.` instead of `${workspaceRoot}:.`
Don't use semicolons on Linux. :sweat_smile:

**Comment by customBoks** [comment]
i compile my file "javac TestJava.java" in the terminal of vscode and try your different solutiuon javac -g TestJava.java but it's same , sorry when you saw "manualy "wht s the signification ? sorry for list of question my friend :)

**Comment by customBoks** [comment]
yes you right i forget to replace

**Comment by faustinoaq** [comment]
Never mind, just compile your java file. When your `.class` file is generated you should be able to debug it.

**Comment by customBoks** [comment]
oooo this working , you are a genius my friend , just i a replace ";"  and it works.
for Windows it's  _;_ and for Linux it's  _:_ 

merci beaucoup
 
and good choise for your KDE system ;)

**Comment by customBoks** [comment]
milles merci for the master student who you are if i could help you one day in your timeline i jump on it

Bye
