### ISSUE TITLE
Cant get the debugger running for a maven project 

### ISSUE THREAD

**Issue by jakara** [DonJayamanne/javaVSCode#29]
I'm using the Java Debugger 0.0.2 on vscode 1.10.2 on windows 10, when i press F5 , error pop up: **Debugger failed to attach: handshake failed - connection prematurally closed**
and then nothing happen, no breakpoints hit.

It's pretty simple code just:
```
package com.jakara.app;

public class App
{
    public static void main( String[] args )
    {
        System.out.println( "Hello World!" );

        int i = 3 + 44;

        System.out.println(i);
    }
}
```
and  my lanch config:

```
{
    "version": "0.2.0",
    "configurations": [{
        "name": "Java",
        "type": "java",
        "request": "launch",
        "stopOnEntry": true,
        "cwd": "${workspaceRoot}/src",
        "startupClass": "com.jakara.app.App",
        "options": [
            "-classpath",
            "${workspaceRoot}/target/classes"
        ],
        "externalConsole": true,
        "jdkPath": "${env:JAVA_HOME}/bin",
        "preLaunchTask": "compile"
    }]
}
```
and task config:
```
{
    "version": "0.1.0",
    "windows": {},
    "osx": {},
    "command": "mvn",
    "isShellCommand": true,
    "args": [],
    "showOutput": "always",
    "tasks": [{
            "taskName": "clean"
        },
        {
            "taskName": "compile"
        },
        {
            "taskName": "test"
        },
        {
            "taskName": "package"
        },
        {
            "taskName": "verify"
        },
        {
            "taskName": "spring-boot:run",
            "args": [
                "-Drun.profiles=dev"
            ]
        }
    ]
}
```

complie successed, but the debugger doest work, any help?

**Comment by bmrussell** [comment]
Having a lot of trouble with this too:  with Java failing to find the startup class. Classes are under workspace\target\com\company\namespace folder but setting the above or the whole path in launch.json doesn't seem to work.

**Comment by viniciuscr** [comment]
you can try set the source code´s location on launch.json

```
"sourcePath": [
               "${workspaceRoot}/src/" 
            ],
            "jdkPath": "C:\\Program Files\\Java\\jdk1.8.0_121\\bin",
            "stopOnEntry": true, 
           ....
```
It will help out to find the sources for debug but, at least for me, breakpoints are not working. I have set `stopOnEntry:true` in order to stop the execution at the first line of code, then i can use F10 till find the place that i want to debug.

Anyway, it still a not good solution. I am using Vscode to code and debugging on Eclipse :(

**Comment by faustinoaq** [comment]
PR #25 adds maven support

**Comment by faustinoaq** [comment]
See #8
