### ISSUE TITLE
latest version not on marketplace

### ISSUE THREAD

**Issue by pmlopes** [DonJayamanne/javaVSCode#30]
Changelog latest version: 0.1.0
Marketplace latest version: 0.0.2

Any plans to get it released? From the log it looks there are some nice features added.

**Comment by dark2y** [comment]
+1

You can actually build it yourself but here is my build if you don't want to. Just delete the docx part and enjoy :) 

https://github.com/DonJayamanne/javaVSCode/files/933048/javaVSCode.VSIX.docx

**Comment by DonJayamanne** [comment]
oops, I thought it was. will release asap

**Comment by DonJayamanne** [comment]
New version has been published.
