### ISSUE TITLE
Cannot debug spring boot webservice

### ISSUE THREAD

**Issue by danishgarg** [DonJayamanne/javaVSCode#31]
I was able to get the debugger break in the main method (stopOnEntry=true). However I cant seem to be able to make it hit a breakpoint in the controller when a request is made on the server. I think there may be a problem with my configuration. I am using redhat extension for Java also for language support. I am using gradle for dependency resolution and as build script. Here's my launch configuration. I have one to run the fat jar and another to run the .class files by specifying the full classpath from gradle.

![screen shot 2017-03-24 at 11 04 39 pm 1](https://cloud.githubusercontent.com/assets/1710110/24307290/98a14f98-10e9-11e7-8022-0dd1d401eb2c.png)

Here's my task.json file. I have verified that the generated .class files do have all debug symbols (line numbers and vars)

<img width="504" alt="screen shot 2017-03-24 at 11 10 09 pm" src="https://cloud.githubusercontent.com/assets/1710110/24307302/a78773b6-10e9-11e7-8b36-3c95d7910c2a.png">

Your work on this debugger is already much appreciated. Can you help in resolving this issue?

**Comment by faustinoaq** [comment]
See #13
