### ISSUE TITLE
Better Readme request

### ISSUE THREAD

**Issue by lacivert** [DonJayamanne/javaVSCode#34]
As a newcomer, I would like to see what I should do after install the extension. I see that I have to do something like "tasks.json" etc but I don't really know what is it and where it should stay (is it a new file a directory in file system? or a current file to change? where should I find it? etc) So, instructions should be more clear and specific in order to use the extension more effectively.

**Comment by bmrussell** [comment]
Hi lacivert.

tasks.json controls external tools - ie what you'd use to build the source you have open in vscode. There's a good walkthrough [here](https://code.visualstudio.com/docs/editor/tasks). It's not specific to java support, but a vscode feature in general, so probably not worth covering in the readme. Though I agree a few samples to help beginners would be welcome.

You can get more vscode extensions that provide maven support for example & these will generate a default tasks.json for a maven project.

**Comment by faustinoaq** [comment]
Please See #3
