### ISSUE TITLE
wrong generated options in launch.json

### ISSUE THREAD

**Issue by ghost** [DonJayamanne/javaVSCode#37]
For Linux it generates:
```json
      "options": [
        "-classpath",
        "\"${fileDirname};.\""
      ]
```
But must:
```json
      "options": [
        "-classpath",
        "${fileDirname}:."
      ]
```
Linux doesn't use semicolons in this case and it doesn't need additional double quotes around `$fileDirname`.

This mismatch creates `Could not find or load main class SomeClass` error.

**Comment by rianadon** [comment]
The double quotes also cause issues in Windows and removing them makes the classpath valid.

**Comment by faustinoaq** [comment]
Fixed via [commit](https://github.com/DonJayamanne/javaVSCode/commit/c9978652e0c0c038ba20d65016239555a1ec271)

This change will ship in next release

**Comment by rianadon** [comment]
Thanks @faustinoaq! I may be incorrect but even with the commit wouldn't semicolons still be present in the default launch configuration under Linux?

If they are then the launch configuration should probably be dynamically generated based on the OS, or the classpath instead specified as an array. If you'd prefer I could submit a PR for either.

**Comment by faustinoaq** [comment]
Yes, a classpath array would be useful here, see: [Java Linter implementation](https://github.com/faustinoaq/vscode-javac-linter/blob/master/server/src/server.ts#L99)
A PR is welcome :smile:

**Comment by rianadon** [comment]
Thank you for the link.
I'll work on a PR and use this issue for any questions I may have :smiley:.
