### ISSUE TITLE
debugging in "java console app" not working

### ISSUE THREAD

**Issue by Ysuran** [DonJayamanne/javaVSCode#4]
hello, when I try debug a java code in "java console app" the extern console is not appear. When i debuggin in "java" ist work fine but i cant insert dates in the console of vs code. 

Sorry for my english i hope that understand me.

**Comment by DonJayamanne** [comment]
Hi, sorry for not removing the  "java console app" from the debug section
This will be supported in the next build.
You can insert (input) data into a console app only via the external console, not via vscode.

**Comment by Ysuran** [comment]
AH. Okay, then I'll be waiting for the next update

**Comment by DonJayamanne** [comment]
Fixed, in both windows and mac
