### ISSUE TITLE
Variables don't appear

### ISSUE THREAD

**Issue by jho53** [DonJayamanne/javaVSCode#49]
For some reason, variables don't show up at all.
For example, in:
```
class Hellothere{
    public static void main(String[] args) {
        int a = 20;
        int b = 30;
        System.out.println(a);
    }
}
```
"a" and "b" should be in the variable window, but it's empty.

**Comment by faustinoaq** [comment]
Hi @CheezyP try to compile your code with debugging support `javac -g Hellothere.java`

![screenshot_20170620_213915](https://user-images.githubusercontent.com/3067335/27364558-ee5d079a-5600-11e7-8d94-3a53bb47cc02.png)

**Comment by jho53** [comment]
Yes, that works. I'm so glad!

On a side note, might want to include that in the readme

**Comment by suriyanS** [comment]
Yes, it Works. Thanks
