### ISSUE TITLE
Can't see any variables

### ISSUE THREAD

**Issue by mhansen** [DonJayamanne/javaVSCode#52]
<img width="957" alt="screen shot 2017-07-03 at 20 40 01" src="https://user-images.githubusercontent.com/105529/27789421-d4189c62-602f-11e7-817f-53485b88b22a.png">

Hi folks, I'm using VS Code May 2017 (version 1.13), and Java Debugger 0.1.2.

I've reproduced this on both Windows and Mac OS X. No Variables show up in the left pane, nor can I hover over variables to see their values.

**Comment by faustinoaq** [comment]
Duplicate, See #49

**Comment by mhansen** [comment]
Thanks, compiling with -g did the trick. Probably want to add this to the README :-)
