### ISSUE TITLE
"Debug adapter process has terminated unexpectedly" and "Failed to start the program, Error: spawn /bin/java ENOENT"

### ISSUE THREAD

**Issue by personinblack** [DonJayamanne/javaVSCode#58]
Hello,
I'm new to VS Code and trying to debug a simple Java program with this debugger.
["launch.json"]( https://hastebin.com/uhibirubid.scala)
[The code I'm trying to run](https://hastebin.com/kujaneyafi.cs)
[The project structure](https://hastebin.com/pezemuwure.css)

I tried both building with Gradle and by javac directly ("javac -g src/main/java/me/menfie/riddle/Riddle.java"). When I set ""externalConsole": true" inside "launch.json" I get the "Debug adapter process has terminated unexpectedly" error and debugger freeze (externalConsole is not starting) and I have to restart VS Code. If I don't set it (comment it out) I get "Failed to start the program, Error: spawn /bin/java ENOENT" and debugger don't run.

**Comment by faustinoaq** [comment]
Your `launch.json` is incorrect at line 10:

```
            "cwd": "${workspaceRoot/bin}", <-- should be "${workspaceRoot}/bin"
```

After that I can debug your project successfully:

![screenshot_20170729_142157](https://user-images.githubusercontent.com/3067335/28747644-c8659bec-7469-11e7-88e9-42332e0507a5.png)
