### ISSUE TITLE
Failed to start the program, Error: spawn /bin/java ENOENT

### ISSUE THREAD

**Issue by clankill3r** [DonJayamanne/javaVSCode#59]
When I try to debug I get the following error:

> Failed to start the program, Error: spawn /bin/java ENOENT

Platform OSX.
The JAVA_HOME is set, if I `echo $JAVA_HOME` I get `/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home` (which exists).

My tasks looks like this:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "type": "shell",
    "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "shared"
    },
    "isBackground": true,
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "build",
            "command": "javac",
            "args": ["-g", "${file}"]
        }
    ]
}
```

and launch looks like this:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Java",
            "type": "java",
            "request": "launch",
            "stopOnEntry": true,
            "preLaunchTask": "build",                 // Runs the task created above before running this configuration
            "jdkPath": "${env:JAVA_HOME}/bin",
            "cwd": "${fileDirname}",
            "startupClass": "${fileBasenameNoExtension}",
            "classpath": [
                ".",
                "${fileDirname}"
            ],
            "args": []
        }
    ]
}
```

This is the code I try to run:

```
import java.util.ArrayList;

public class Test {

    public static void main(String[] args) {
        Test t = new Test();
        t.foo();
    }

    public void foo() {

        ArrayList<?> l = new ArrayList<>();
        ArrayList ll = new ArrayList<>();
        System.out.println("Foo!");
        System.out.println("Bar!");
        System.out.println("End!");
    }

}
```
(O yeah, the readme of this repository contains a lot of fields that are deprecated).

**Comment by faustinoaq** [comment]
> (O yeah, the readme of this repository contains a lot of fields that are deprecated).

Yes, a better README is needed. :sweat_smile: 

![screenshot_20170802_104203](https://user-images.githubusercontent.com/3067335/28881899-3c4e5ffa-776f-11e7-80e8-886996180de2.png)

I don't know what is your issue, I was able to debug your java code with the config you show me.  

On Linux `JAVA_HOME` is `/usr/lib/jvm/default` and works well. :sweat_smile:

**Comment by clankill3r** [comment]
In case it helps:

This is the terminal output:

> \> Executing task: javac -g /Users/doekewartena/Desktop/temp/VSCODE_tests/java/Test.java <
> 
> Terminal will be reused by tasks, press any key to close it.

**Comment by faustinoaq** [comment]
The terminal output show that your `javac` is working well.

Maybe you should replace `"${env:JAVA_HOME}/bin"` by an absolute path where `bin` folder is located.

**Comment by clankill3r** [comment]
Yeah that worked!
Is that a bug in VSCode?

**Comment by faustinoaq** [comment]
Maybe, I don't know, my VSCode is working well with `"${env:JAVA_HOME}/bin`

**Comment by faustinoaq** [comment]
> Yeah that worked!

**Comment by ManushaBethelli** [comment]
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Java",
            "type": "java",
            "request": "launch",
            "stopOnEntry": true,
            "jdkPath": "${env:JAVA_HOME}",
            "cwd": "${fileDirname}",
            "startupClass": "${fileBasenameNoExtension}",
            "classpath": [
                ".",
                "${fileDirname}"
            ]
        },
        {
            "name": "Java Console App",
            "type": "java",
            "request": "launch",
            "stopOnEntry": true,
            "jdkPath": "${env:JAVA_HOME}",
            "cwd": "${fileDirname}",
            "startupClass": "${fileBasenameNoExtension}",
            "classpath": [
                ".",
                "${fileDirname}"
            ],
            "externalConsole": true
        }
    ]
}

Here is my launch.json. When I try to start debugger, it says 
Error: Could not find or load main class Authors
Any thoughts ?

**Comment by faustinoaq** [comment]
Try replacing `"jdkPath": "${env:JAVA_HOME}",` by `"jdkPath": "${env:JAVA_HOME}/bin",`

**Comment by ManushaBethelli** [comment]
That was the initial generated thing and I did replace it to "jdkPath": "${env:JAVA_HOME}".
With "jdkPath": "${env:JAVA_HOME}/bin", I see
<img width="1037" alt="screen shot 2017-09-19 at 10 37 29 pm" src="https://user-images.githubusercontent.com/19477595/30625807-29622eca-9d8b-11e7-8007-1f125ab67eae.png">

**Comment by faustinoaq** [comment]
Ok, try to use absolute path for JDK instead

**Comment by ManushaBethelli** [comment]
Tried that too. It goes back to my initial issue again :(
Error: Could not find or load main class Authors

**Comment by ManushaBethelli** [comment]
Never mind. I think I have an issue with my Java file. Tried with a new one and that worked.
Thanks for quick response.
