### ISSUE TITLE
Can we debug android applications?

### ISSUE THREAD

**Issue by airstep** [DonJayamanne/javaVSCode#6]
Hi!

There are many instructions for android app console debugging. But can we attach this to vscode?

Look at this please:  https://codeseekah.com/2012/02/16/command-line-android-development-debugging/

What you think?

**Comment by DonJayamanne** [comment]
Hi Thanks, for that link. I have had a brief look at Android debugging using this approach and am interested in it. I will look into this soon, by soon i mean in around 2 weeks, as I'm quite busy with some personal commitments at this stage. sorry.
Do keep the suggestions coming.

**Comment by faustinoaq** [comment]
To debug Android use https://marketplace.visualstudio.com/items?itemName=adelphes.android-dev-ext
