### ISSUE TITLE
Need help on how to use this debugger

### ISSUE THREAD

**Issue by pbkay** [DonJayamanne/javaVSCode#63]
Hello. I'm a little lost on how to use this debugger. I was watched the gifs on the 'readme' page and whenever I clicked the green-play button, it doesn't look like the gif.

Some questions I have:

1. I placed the red dot on the side but the debugger starts debugging at the beginning of my code?
2. How do I watch a variable?

This is what my screen looks like after I press the play button.

![1](https://user-images.githubusercontent.com/20728761/29187725-a8e31ca8-7dc5-11e7-86ac-bb2ddf50a4a2.PNG)

**Comment by faustinoaq** [comment]
Just compile with `javac -g` to enable debug info.

Read the README again (see the `-g`)

```json
{
    "version": "0.1.0",
    "command": "javac",
    "isShellCommand": true,
    "showOutput": "always",
    "isWatching": true,
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "build",
            "args": ["-g", "${file}"]
        }
    ]
}
```

**Comment by pbkay** [comment]
I changed it to this and it still doesn't show info? 

```
{
    "version": "2.0.0",
    "type": "shell",
    "presentation": {
        "echo": true,
        "reveal": "always",
        "focus": false,
        "panel": "shared"
    },
    "isBackground": true,
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "build",
            "command": "javac",
            "args": ["javac -g", "${file}"]
        }
    ]
}
```

**Comment by faustinoaq** [comment]
I don't know what would be the problem 😅
