### ISSUE TITLE
Can not debug project

### ISSUE THREAD

**Issue by nengc** [DonJayamanne/javaVSCode#68]
My project is spring-boot Maven project。 And can run correctly。But when i debug it，can not setup，only show like below：
![image](https://user-images.githubusercontent.com/19792047/29900759-5d9e9850-8e26-11e7-80c9-b08be08bc215.png)

It is in fake debug mode。Here are my tasks.json and launch.json
![image](https://user-images.githubusercontent.com/19792047/29900835-d4514d12-8e26-11e7-9b28-12078fc0eb47.png)
![image](https://user-images.githubusercontent.com/19792047/29900840-dff41b72-8e26-11e7-973b-e52864c925c7.png)

**Comment by ghost** [comment]
Please, see [these helpful comments](https://github.com/DonJayamanne/javaVSCode/issues/13#issuecomment-312088100) by @khe817 on #13
