### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by HugHoo** [DonJayamanne/javaVSCode#7]
Here is my launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "jdkPath": "C:\\Software\\java\\JDK\\bin",
            "name": "Java",
            "type": "java",
            "request": "launch",
            "stopOnEntry": true,
            "cwd": "${fileDirname}",
            "startupClass": "${fileBasename}",
            "options": [
                "-classpath",
                "\"${fileDirname};.\""
            ]
        },
        {
            "jdkPath": "C:\\Software\\java\\JDK\\bin",            
            "name": "Java Console App",
            "type": "java",
            "request": "launch",
            "stopOnEntry": true,
            "cwd": "${fileDirname}",
            "startupClass": "${fileBasename}",
            "options": [
                "-classpath",
                "\"${fileDirname};.\""
            ],
            "externalConsole": true
        }
    ]
}
```

I add "jdkPath" according to the Requirements, but the debugger still not working.
Hope help and more details about configuration.
(by the way, my English is shit... I'm a Chinese student)

**Comment by DonJayamanne** [comment]
Please could you describe the problem. Are any errors being displayed, if so what are they?

**Comment by HugHoo** [comment]
Thanks for your reply.
I recorded a .gif for explaining the problem.

<img src="https://raw.githubusercontent.com/HugHoo/hexo_ooho/master/source/_posts/test.gif" />

<img src="https://raw.githubusercontent.com/HugHoo/hexo_ooho/master/source/_posts/%E6%9C%AA%E5%91%BD%E5%90%8D%E5%9B%BE%E7%89%87.png" />

**Comment by hlxkurapika** [comment]
I meet the same promble.

**Comment by faustinoaq** [comment]
@HugHoo @hlxkurapika you solved this?
I'm using with javaVSCode now and works well.

**Comment by DonJayamanne** [comment]
Will close. If problem persists please re-open.
