### ISSUE TITLE
need config to only 'run' the java file

### ISSUE THREAD

**Issue by GorvGoyl** [DonJayamanne/javaVSCode#70]
Hi,
I can successfully debug java files but don't know the config to just run.
Can I have launch.json/tasks.json config to run java file?

**Comment by faustinoaq** [comment]
Yeah, you don't even need this extension just using `tasks.json`

In addition you can set in your `launch.json`:

```json
{
    ...
    "stopOnEntry": false,
    ...
}
```

and use the debugger to run java code without debugging :stuck_out_tongue_winking_eye:

**Comment by GorvGoyl** [comment]
got it.
