### ISSUE TITLE
src/main/java directory structure is hardcoded for package names

### ISSUE THREAD

**Issue by mrawdon** [DonJayamanne/javaVSCode#74]
The directory path structure src/main/java is [hardcoded](https://github.com/DonJayamanne/javaVSCode/blob/b21c5a73baeaff8ece4c9e7958e163ce3b8a60cd/src/client/jdb.ts#L91).  This isn't how my projects are setup so it won't work in my environment.

If this were moved to a property I could configure this to work easily in my projects.  Ideally this would be done with a regex allowing me to use a single launch configuration for multiple projects,

**Comment by faustinoaq** [comment]
Fixed via #75
