### ISSUE TITLE
"Failed to start the program, Timeout after 5000 milli-seconds" & The system cannot find the path specified.

### ISSUE THREAD

**Issue by RyanHope97** [DonJayamanne/javaVSCode#76]
So I've been trying to get a simple "Hello World!" program to run in the debugger for the past few days, and I can't get it to run by just running the debugger. 

Here is my folder structure: ![untitled](https://user-images.githubusercontent.com/25053594/30559099-68975150-9cab-11e7-9e8b-5081cc31f044.png)

Here are my launch.json and tasks.json: ![untitled 2](https://user-images.githubusercontent.com/25053594/30559098-6894149a-9cab-11e7-85e7-34ea8673c865.png)

Any help would be appreciated!

Edit: Also when I change externalConsole to false I get "Failed to start the program, Error: spawn \bin\java ENOENT"

**Comment by RyanHope97** [comment]
I have fixed the issue by changing"jdkPath" to "D:/Program Files/Java/jdk1.8.0_144/bin". I'm now wondering how you set the set JAVA_HOME enviroment variable?

**Comment by faustinoaq** [comment]
> how you set the set JAVA_HOME enviroment variable?

You need to set this in Advanced System Settings on Control Panel
