### ISSUE TITLE
Buggy debugging for Spring Boot applications caused by the new released version (0.1.4)

### ISSUE THREAD

**Issue by khe817** [DonJayamanne/javaVSCode#79]
New released version of the debugger (0.1.4) broke something related to debugging multi-threaded processes.

Now to run the remote debugger for Spring Boot applications, I have to follow some extra steps:

- Run Spring Boot web app server with opened port 5005 for debugging:
```
$ mvn spring-boot:run -Drun.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"
```
- Add a break point in a controller's method. The controller file must be the currently focused window in VSCode.
- Run the debugger (`F5`).
- Restart the debugger (`Ctrl + Shift + F5`) once the application is started up & running. (<~~ This is the part where I supposed it's buggy, not sure if it's supposed to happen)
- Hit Pause (`F6`), then Run (`F5`) the debugger again. (<~~ this one too)
- Call to that controller in browser/cli (e.g. `$ curl  localhost:8080/greeting/`).
- The debugger will stop at the break point in the controller.
- Debugging things.

My launch.json configurations are still the same as the one in issue #13 :
 ```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Java Remote",
            "jdkPath": "${env.JAVA_HOME}/bin",
            "type": "java",
            "request": "attach",
            "stopOnEntry": true,
            "cwd": "${workspaceRoot}/src/main/java",
            "startupClass": "${relativeFile}",
            "sourcePath": ["${workspaceRoot}/src/main/java"],
            "classpath": ["${workspaceRoot}/target/classes"],
            "remoteHost": "localhost",
            "remotePort": 5005
        }
    ]
}

```

Pros is now I can attach and detach the debugger multiple times after the application starts up for debugging. I.e. I could edit the code, then run the debugger again without having to restart Spring Boot. Which is nice!

**Comment by khe817** [comment]
I have figured it out. There is nothing wrong with the debugger. There is a new launch configuration `startupClassPathPattern` that I should use to make it debug normally.

My new launch.json:
 ```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Java Remote",
            "jdkPath": "${env.JAVA_HOME}/bin",
            "type": "java",
            "request": "attach",
            "stopOnEntry": true,
            "cwd": "${workspaceRoot}",
            "startupClass": "${relativeFile}",
            "startupClassPathPattern": "src/main/java/",
            "sourcePath": ["${workspaceRoot}/src/main/java"],
            "classpath": ["${workspaceRoot}/target/classes"],
            "remoteHost": "localhost",
            "remotePort": 5005
        }
    ]
}

```

**Comment by faustinoaq** [comment]
@khe817 Your issues are very helpful, Thanks you for contribute! 👍
