### ISSUE TITLE
Time to deprecate this extension

### ISSUE THREAD

**Issue by DonJayamanne** [DonJayamanne/javaVSCode#80]
@faustinoaq Its with a sad heart I say this, but it must be said. We will have to stop supporting this extension as Microsoft have released their own [extension with debug support for Java.](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug)

Let me know when you think we should stop supporting this extension.
I'd suggest creating one last release and updating the readme with a deprecation notice, pointing users to the new Microsoft extension.

**Comment by faustinoaq** [comment]
@DonJayamanne Yeah, you are right,  I'm using the new debug extension for Java now. Thanks you for you support, this extension helped me a lot.

> I'd suggest creating one last release and updating the readme with a deprecation notice, pointing users to the new Microsoft extension.

I agree, no problem, we should avoid duplicated work 👍

**Comment by DonJayamanne** [comment]
@faustinoaq thanks.  Been a pleasure
