### ISSUE TITLE
Error: Could not find or load main class BeerSong

### ISSUE THREAD

**Issue by GeekChao** [DonJayamanne/javaVSCode#9]
I add jdk path:  "jdkPath": "/Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin", and task.json for building.

When I debug the code, the error messages pop up, that is, "Error: Could not find or load main class BeerSong:. I can not solve this problem, can you help me out?

Moreover, when I try to build .class file, it doesn't work either even though I just copy your configuration. However, if I replace "$(file)" with the name of my java file, it can generate .class file.            

I am the new one to use the visual code. One suggestion, can you provide more specific installation and configuration tutorial? In my case, I spent much time figuring out how to add launch.json and what task.json is. 

Thanks in advance.

**Comment by DonJayamanne** [comment]
Well check this out today.
